# -*- coding: utf-8 -*-
"""AML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13lIw9ZNA9AV_eZLntqNbTX4eGaD8WXbY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import joblib

df = pd.read_csv("movies.csv")

print(df.head())
print(df.columns)

df = df[['budget', 'revenue', 'runtime', 'genres', 'release_date', 'vote_average']]

df = df.dropna()
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')
df['year'] = df['release_date'].dt.year
df = df.dropna()

import ast

def extract_genre(x):
    try:
        genres = ast.literal_eval(x)
        return genres[0]['name'] if len(genres) > 0 else 'Unknown'
    except:
        return 'Unknown'

df['genres'] = df['genres'].apply(extract_genre)

df['genres'] = df['genres'].astype('category').cat.codes

df['success'] = (df['revenue'] > df['budget'] * 2).astype(int)

sns.countplot(x='success', data=df)
plt.title("Movie Success Distribution")
plt.show()

X = df[['budget', 'runtime', 'genres', 'year', 'vote_average']]
y = df['success']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

joblib.dump(model, "model.pkl")
joblib.dump(scaler, "scaler.pkl")

import streamlit as st
import joblib
import numpy as np

model = joblib.load("model.pkl")
scaler = joblib.load("scaler.pkl")

st.title("🎬 Movie Success Predictor")

budget = st.number_input("Budget", min_value=1000)
runtime = st.number_input("Runtime", min_value=60)
genre = st.number_input("Genre Code (0,1,2...)")
year = st.number_input("Year", min_value=1900)
rating = st.number_input("Vote Average (0-10)", min_value=0.0, max_value=10.0)

if st.button("Predict"):
    data = np.array([[budget, runtime, genre, year, rating]])
    data = scaler.transform(data)

    prediction = model.predict(data)

    if prediction[0] == 1:
        st.success("🎉 HIT Movie!")
    else:
        st.error("❌ FLOP Movie")

