# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vDICY8anLcSZ_PWHhrIevWSVPEL9pV70
"""

import pandas as pd

df = pd.read_csv("movies.csv")
df.head()
df.info()
df.describe()

df.isnull().sum()

df = df.dropna()

df['budget'].fillna(df['budget'].median(), inplace=True)
df['runtime'].fillna(df['runtime'].mean(), inplace=True)

df = df.drop_duplicates()

df['release_date'] = pd.to_datetime(df['release_date'])

df['year'] = df['release_date'].dt.year

df['profit'] = df['revenue'] - df['budget']

df['success'] = df['revenue'].apply(lambda x: 1 if x > 100000000 else 0)

import ast

def extract_genre(x):
    try:
        genres_list = ast.literal_eval(x)
        return genres_list[0]['name'] if len(genres_list) > 0 else 'Unknown'
    except:
        return 'Unknown'

df['genres'] = df['genres'].apply(extract_genre)

df['genres'] = df['genres'].astype('category').cat.codes

df = df.drop(['id', 'title', 'overview'], axis=1, errors='ignore')

X = df[['budget', 'runtime', 'genres', 'year', 'profit']]
y = df['success']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)
y_pred_dt = dt.predict(X_test)
y_pred_rf = rf.predict(X_test)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

print("\nLogistic Regression Report:\n", classification_report(y_test, y_pred_lr))
print("\nDecision Tree Report:\n", classification_report(y_test, y_pred_dt))
print("\nRandom Forest Report:\n", classification_report(y_test, y_pred_rf))

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred_rf)

sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix - Random Forest")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

rf = RandomForestClassifier(n_estimators=200, max_depth=10)
rf.fit(X_train, y_train)